temenostech/IRIS

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java

When there are chained auto transitions e.g. a --> b --> c the iris output reflects the target resources data except for the term attribute of the category element; the term attribute reflects the term of the first auto transition i.e. b in the example above

https://github.com/temenostech/IRIS/issues/183

---

interaction-dsl/com.temenos.interaction.rimdsl.tests/src/com/temenos/interaction/rimdsl/GeneratorSpringPRDTest.java
interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/generator/RIMDslGeneratorSpringPRD.xtend
interaction-dsl/interaction-springdsl/src/main/resources/IRIS-SpringDSL-main.xml

to make it easier for a spring factory to find them with a wildcard pattern.

Move properties files down into META-INF

---

interaction-core/src/main/java/com/temenos/interaction/core/resource/ConfigLoader.java
interaction-core/src/main/java/com/temenos/interaction/core/resource/ResourceMetadataManager.java
interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/SpringDSLPropertiesFactoryBean.java
interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/SpringDSLResourceStateProvider.java
interaction-dsl/interaction-springdsl/src/main/resources/IRIS-SpringDSL-main.xml

Switched on by specifying JVM option: -Dcom.temenos.interaction.config.dir=

Adding support for loading IRIS configuration files from the file system

---

interaction-dsl/com.temenos.interaction.rimdsl.generator/pom.xml
interaction-dsl/com.temenos.interaction.rimdsl.parent/pom.xml
interaction-dsl/com.temenos.interaction.rimdsl.tests/META-INF/MANIFEST.MF
interaction-dsl/com.temenos.interaction.rimdsl.ui/META-INF/MANIFEST.MF
interaction-dsl/com.temenos.interaction.rimdsl.visualisation/META-INF/MANIFEST.MF
interaction-dsl/com.temenos.interaction.rimdsl/META-INF/MANIFEST.MF
interaction-dsl/com.temenos.interaction.rimdsl/pom.xml
interaction-parent/pom.xml
interaction-sdk-plugin/pom.xml
interaction-sdk-rim-plugin/pom.xml

Note xtext and xtend are in sync: xtend depends on xtext.
We used to use a 'xtend-standalone' jar, which has been discontinued from 2.5
So there is now an additional dependency on org.eclipse.equinox.common

Upgrade to XText 2.8.3

---

interaction-dsl/com.temenos.interaction.rimdsl.generator/pom.xml

This dependency was previously pulled in by the xtend-standalone. It is still implicitly a dependency, but somehow the build is getting confused as to where to pull it from, leading to intermittent failures on the CI server.

Explicitly add xbase as a dependency

---

interaction-parent/pom.xml
interaction-winkext/pom.xml
useragent-examples/useragent-swagger-ui/pom.xml

Reason for this change is spring-security gives the warning for existing version of spring-bean version and recommended to update the spring-bean version to 3.2.13.RELEASE

spring bean version updated to 3.2.13.RELEASE

---

interaction-parent/pom.xml

The restlet libraries are not on maven central, a clean build needs a specific location for them.
Also spell out the halbuilder versions, which can break easily depending on maven settings.

Point at moved maven repo for restlet, fix halbuilder versions

---

interaction-core/src/main/java/com/temenos/interaction/core/entity/MetadataParser.java
interaction-core/src/main/java/com/temenos/interaction/core/resource/ResourceMetadataManager.java
interaction-odata4j-ext/src/main/java/com/temenos/interaction/odataext/entity/MetadataOData4j.java

If a metadata-*.xml file has a Property element without a Name
attribute, that's an error. It took me hours to find it didn't
work because I'd used name= instead of Name=
Also add some debug-level logging around the parsing

Raise an exception if an EDM metadata property lacks a name

---

interaction-sdk-plugin/pom.xml
interaction-sdk-plugin/src/main/java/com/temenos/interaction/sdk/plugin/ResponderGenMojo.java

Added support for Maven 3.3 by introducing redundant annotation based Mojo configuration for ResponderGenMojo + renaming some variables to match parameter name. Looks like regression in Maven 3.3 comparing to 3.0.5, but as the above changes help - probably no point investigating into Maven.

Support for Maven 3.3

---

interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALMediaType.java
interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestHALProvider.java

The application/json media type was previously supported for output, but did not work for input
Simplified the media type handling generally in HALProvider. As a side-effect, the charset parameter on the media type is now properly supported.
The RepresentationFactory used by the HALProvider can now be defined in the spring configuration if non-standard behaviour is required. The default behaviour is unchanged

Support application/json in HALBuilder

---

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/ResourceStateMachine.java
interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestResourceStateMachine.java

Fix to remove double encoding of the links. Added unit tests to support href's containing HTTP character entities specified in RFC 3986 except * because it's not being supported by URLEncoder.

Fix to remove double encoding of the links. Added Unit tests to test the same.

---

interaction-core/src/main/java/com/temenos/interaction/core/ExUriInfoImpl.java
interaction-core/src/main/java/com/temenos/interaction/core/UriInfoImpl.java
interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomXMLProvider.java
interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestAtomXMLProvider.java

In case of the string have special characters encoded, this revert the encoded received to the original form. This is needed because, to find a proper state in the resource state machine, its used string compare.

Decoding the string resourcePath from UTF8

---

interaction-core/src/main/java/com/temenos/interaction/core/UriInfoImpl.java

The AtomXMLProvider decodes the endpoint to UTF-8 but not the path parameters. With this fix, both are decoded to the correct charset to be handled by IRIS.

Fix to decode the path parameters from the endpoint received

---

interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/ODataLinkInterceptor.java
interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestAtomXMLProvider.java
interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestODataLinkInterceptor.java

Due to over enthusiastic removal of duplicate links when they have same HRef and Rel but different Id (See RTC 1674338).

Missing drill downs under payment information.

---

interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomEntityEntryFormatWriter.java
interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomXMLProviderHelper.java
interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/AtomXMLProviderHelperTest.java

The class cast exception has been happening in the integration tests as the JPAProducer always produces with entities with joda LocalDateTime as the type but the casting is always to java util Date.

Fixing class cast exception on datetime type handling in atom xml

---

useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/AtomLinkHandler.java
useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/AtomLinkHandlerTest.java
useragent-generic-java/src/test/resources/atom_entry_with_embedded_empty_inline_link.txt

Prevents PayloadHandler from throwing ArrayIndexOutOfBoundsExceptions when
an embedded link contains an empty inline element.

Fix for embedded links with empty inline elements

---

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java
interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkGenerator.java
interaction-examples/interaction-hateoas-dynamic/src/test/java/com/interaction/example/hateoas/simple/HypermediaITCase.java

Resolved target is now added to the transition for dynamic resource.
As part of this exercise have also refactored the code.
Had to comment the an assert in HypermediaITCase because HALProvider is assuming that dynamic links "rel" has "self" but isn't. A separate defect with RTC # 1720030 has been filed to handle this.

Rtc 1706736 Resolved target is now added to the transition for dynamic resource

---

interaction-winkext/src/main/java/com/temenos/interaction/winkext/LazyResourceDelegate.java
interaction-winkext/src/test/java/com/temenos/interaction/winkext/TestLazyResourceDelegate.java
interaction-winkext/src/test/java/com/temenos/interaction/winkext/TestLazyServiceRootFactory.java

Fix the LazyResourceDelegate method getResource to resolve the resource state without decoding the uri path.
This avoids the problem when IRIS receives an URL with a parameter that contains special characters encoded like "/".

Fix the LazyResourceDelegate to force the usage of the non decode path

---

interaction-core/src/main/java/com/temenos/interaction/core/rim/HeaderHelper.java
interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHeaderHelper.java

This change has been made to prevent IRIS from rendering an incomplete
location header.

Throw RuntimeException if encoding is unsupported

---

interaction-core/src/main/java/com/temenos/interaction/core/rim/HeaderHelper.java
interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHeaderHelper.java

HeaderHelper now prepends either a & or a ? depending on whether the
incoming target URL already has query parameters or not.

Prepend ? or & to query parameters

---

interaction-odata4j-ext/src/main/java/org/odata4j/format/xml/AtomFeedFormatParserExt.java
interaction-odata4j-ext/src/test/java/org/odata4j/format/xml/AtomFeedFormatParserExtTest.java

All odata link flowing into the IRIS response should be consumed while using the extended the Odata4j-ext library

interaction-odata4j-ext fix for consume all the links (with any relation)

---

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/ResourceStateMachine.java
interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/expression/ResourceGETExpression.java
interaction-core/src/main/java/com/temenos/interaction/core/resource/CollectionResource.java
interaction-core/src/main/java/com/temenos/interaction/core/resource/EntityResource.java
interaction-core/src/main/java/com/temenos/interaction/core/resource/RESTResource.java
interaction-core/src/main/java/com/temenos/interaction/core/rim/ShallowCopyable.java
interaction-core/src/test/java/com/temenos/interaction/core/resource/TestCollectionResource.java
interaction-core/src/test/java/com/temenos/interaction/core/resource/TestEntityResource.java
interaction-core/src/test/java/com/temenos/interaction/core/rim/TestResponseHTTPHypermediaRIM.java

This commit segregates the EntityResource clone method into a separate
interface, implemented in EntityResource and CollectionResource. Cloned
resource objects should be used with expressions to prevent attributes
from being overwritten even when the condition evaluates to false.

Expressions should not overwrite ER attributes

---

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java
interaction-core/src/main/java/com/temenos/interaction/core/web/RequestContext.java
interaction-core/src/main/java/com/temenos/interaction/core/web/RequestContextFilter.java
interaction-core/src/test/java/com/temenos/interaction/core/web/TestRequestContext.java

The parameter is set in the InteractionContext as an attribute since the header "x-jax-rs-hateoas-options" is not a standard http header.

RequestContext class made immutable

---

useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/AtomLinkHandler.java
useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/AtomLinkHandlerTest.java
useragent-generic-java/src/test/resources/atom_entry_with_embedded_self_link.txt

Using the atom xml payload handler in AtomLinkHandler when no content type is available in the link element.
The content type of links in an atom document in an http response is not always same as the content type in the response header.

Content type for atom xml self link

---

interaction-parent/pom.xml

Add scm info to parent POM file.
Add Maven javadoc and sources plugins to parent POM file.

Issue 276 compliance fixes for maven central

---

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/ResourceStateMachine.java

This commit reduces the severity of a logging call in
ResourceStateMachine.injectLinks to INFO from WARN.

1801224 reduce RSM logger call to INFO

---

interaction-media-odata-xml/pom.xml
interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomXMLProvider.java
interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestAtomXMLProvider.java

Set the Content-Length response header in AtomXMLProvider to the size of
the generated document.

1842917 Set Content-Length response header

---

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java
interaction-core/src/test/java/com/temenos/interaction/core/rim/TestResponseHTTPHypermediaRIM.java

This commit alters the behaviour of HTTPHypermediaRIM to continue evaluating autotransitions
in a failure scenario when further autotransitions are possible.

1859482 evaluate auto-transitions after failure

---

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java
interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkGeneratorImpl.java

- Given: A RIM for a resource with three transition properties A, B and C
- When: The resource is requested
- Then: Literal transition properties declared in the RIM must overwrite identically named request query parameters when links' href attributes are built

1854765 literal transition properties take precedence

---

interaction-dsl/com.temenos.interaction.rimdsl.generator/pom.xml
interaction-dsl/com.temenos.interaction.rimdsl.generator/src/main/java/com/temenos/interaction/rimdsl/generator/launcher/Generator.java
interaction-dsl/com.temenos.interaction.rimdsl.generator/src/test/java/com/temenos/interaction/rimdsl/generator/launcher/GeneratorTest.java
interaction-dsl/com.temenos.interaction.rimdsl.tests/src/Simple.rim
interaction-dsl/com.temenos.interaction.rimdsl.tests/src/api-docs-SimpleDomain-Simple.json
interaction-dsl/com.temenos.interaction.rimdsl.tests/src/apiSimple.rim
interaction-dsl/com.temenos.interaction.rimdsl.tests/src/com/temenos/interaction/rimdsl/SwaggerGeneratorTest.java
interaction-dsl/com.temenos.interaction.rimdsl.tests/src/com/temenos/interaction/rimdsl/formatting/FormatterTest.java
interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/RIMDsl.xtext
interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/formatting/RIMDslFormatter.java
interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/generator/RIMDslGeneratorSwagger.xtend
interaction-sdk-rim-plugin/src/main/java/com/temenos/interaction/sdk/plugin/RIMGeneratorMojo.java

Changes:
1. Extension of the rim grammar to enable the usage of annotations. The first usage of the annotation is to create some parts of the swagger api document based on the annotations present on the RIM.
2. Enable on swagger document generation time, the read of metadata to create the schema definition used on the document. This allows to map resources to the actual entity used and present them on the swagger UI.
3. Refactor of the actual swagger generator in order to produce a document that:
Follows the swagger 2.0 spec
- Brings to the Swagger UI the schema definition associated with the operation/method used based on the metadata for the entity defined on the RIM
- Generates multiple documents for multiples RIM's (different api's) and enhances the Swagger UI experience allowing the …

1883279 - Swagger Refactor

---

interaction-examples/interaction-hateoas-banking/src/test/java/com/interaction/example/hateoas/banking/HypermediaITCase.java
interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestHALProvider.java

1883357/1886870 - Remove the validation on self link from HALProvider. It is not mandatory to exclude self links from the body of a request nor have self links matching the requested resource. 
There is also nothing mentioned in the HAL specification document for links in HTTP requests.

1883357 - Remove validation on self link from HalProvider

---

interaction-core/src/test/java/com/temenos/interaction/core/command/TestMatchCommand.java

Re PR #487 , there are tests here for MatchCommand, including a few ignored tests that I think represent bugs. All the non-ignored tests pass on the current code.

Add unit tests for MatchCommand

---

interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java

**1932287:**
Remove the toString allows the provider to return the data type defined by the entity metadata
**Enhancement:**
If a field is marked as mandatory on IRIS metadata (TermMandatory = true) we should return the value, even if the value is a null object.

1932287 - Changes on hal provider

---

useragent-examples/useragent-swagger-ui/src/main/java/com/temenos/useragent/example/swagger/servlet/SwaggerServlet.java
useragent-examples/useragent-swagger-ui/src/test/java/com/temenos/useragent/example/swagger/SwaggerTest.java

Added configurable api_key to the open API document to enable the Authorize menu on Swagger UI. (runtime test of the service on Swagger UI)
The api_key name can be configured the init-param on web.xml file of the container. If not defined the api_key name is setted to the default. Example:
```
<servlet>
<servlet-name>SwaggerServlet</servlet-name>
<servlet-class>com.temenos.useragent.example.swagger.servlet.SwaggerServlet</servlet-class>
<init-param>
<param-name>irisUrlMapping</param-name>
<param-value>Test.svc</param-value>
</init-param>
<init-param>
<param-name>apiKeyTokenName</param-name>
<param-value>mytokenname</param-value>
</init-param>
<load-on-startup>2</load-on-startup>
</servlet>
```

2018558 - Enable the Authorize button on Swagger UI

---

interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/generator/RIMDslGeneratorSwagger.xtend

Fix the regex in swagger to capture the placeholders from the RIM.
The current regex only captures the first element of the group.

2023410 - Swagger Generator

---

interaction-core/src/main/java/com/temenos/interaction/core/web/RequestContext.java
interaction-core/src/test/java/com/temenos/interaction/core/web/TestRequestContext.java

Enhancement 1990960. The getAllHeaders() of RequestContext can be used to access headers which are provided in client request.

Rtc 1999519

---

interaction-odata4j-ext/src/main/java/com/temenos/interaction/odataext/entity/MetadataOData4j.java
interaction-odata4j-ext/src/test/java/com/temenos/interaction/odataext/entity/TestMetadataOData4j.java
interaction-odata4j-ext/src/test/resources/metadata-Customer.xml
interaction-odata4j-ext/src/test/resources/metadataNoModelName.xml

The namespace used in the EDMX document (from $metadata) which includes the model name must be set/created after the metadata model name is made available. Prior to this change, namespace was set to nullModels as model name is not set when metadata is created using a resourceMetadataManager.

RTC2038517 - Setting namespace used in EDMX document after model name is available

---

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/transition/EntityPropertiesGenerator.java

* EntityTransformer can return a null map of properties which, when merged into transition properties, results in NPE.

Fix unit test failures with NPE for null properties

---

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java

* Only when resource state changed through auto transition should we update the http location
header. Location header set and returned with 2xx status would mean the resource state
has been changed and user agent might want to know about it.

Location header updated only when resource state changed

---

interaction-core/src/main/java/com/temenos/interaction/core/workflow/AbortOnErrorWorkflowStrategyCommand.java
interaction-core/src/main/java/com/temenos/interaction/core/workflow/InteractionWorkflowStrategyCommand.java
interaction-core/src/main/java/com/temenos/interaction/core/workflow/TransitionWorkflowStrategyCommand.java

* All interaction commands in auto transitions are executed instead of
only transition commands hence effectively bringing back the auto
transition execution logic that was changed in the meantime to only
support transition commands.
* With this change, any command implementing InteractionCommand would be
executed as part of auto transition.

Fix executing interaction commands for auto transitions

---

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/HypermediaTemplateHelper.java
interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestHypermediaTemplateHelper.java

Fix for 2192855 - Filter parameter is not generated properly for MATCHES operator

RTC-2192855 - Filter parameter is not generated properly for MATCHES operator in rim files

---

interaction-dsl/com.temenos.interaction.rimdsl.parent/pom.xml

Since we are facing the below reported issue we tried the suggested solution but again that bump we always run into signature validation errors. so as suggested other solution in the defect ticket page https://github.com/eclipse/xtext/issues/1231 updating it

To resolve 201802 build issue updating equinox version to 3.8.0

---

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/Link.java
interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLink.java

Trim standard port number while constructing relative url.
http://localhost:80/context to http://localhost/context
https://localhost:443/context to https://localhost/context

Trim standard port number while constructing relative url
