interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java
=> log level changed to debug

interaction-commands-authorization/src/main/java/com/temenos/interaction/commands/authorization/AuthorizationBean.java
=> Follow up fix to 92ef449c8956cc3a2b97b63493be1f35073ea991.

interaction-commands-authorization/pom.xml, interaction-commands-authorization/src/test/java/com/temenos/interaction/commands/authorization/MockAuthorizationBeanTest.java, interaction-commands-solr/pom.xml
Fix some unit tests which failed in build environment.
=> Follow up to 92ef449c8956cc3a2b97b63493be1f35073ea991.

interaction-sdk-test/pom.xml, interaction-sdk-test/src/test/java/com/temenos/interaction/sdk/InteractionSDKTest.java
Fix for the build server issue where the sdk test runs using a different local repo to the main build
=> IRIS-201 pass the local repo to the Verifier for interaction-sdk-test

interaction-commands-authorization/pom.xml, interaction-commands-mule/pom.xml, interaction-commands-odata-bridge/pom.xml, interaction-commands-odata/pom.xml, interaction-commands-solr/pom.xml, interaction-commands-webhook/pom.xml, interaction-core/pom.xml, interaction-dsl/com.temenos.interaction.rimdsl.generator/pom.xml, interaction-dsl/com.temenos.interaction.rimdsl.parent/pom.xml, interaction-dsl/com.temenos.interaction.rimdsl.tests/pom.xml, interaction-dsl/com.temenos.interaction.rimdsl.ui/pom.xml, interaction-dsl/com.temenos.interaction.rimdsl.visualisation/pom.xml, interaction-dsl/com.temenos.interaction.rimdsl/pom.xml, interaction-dsl/interaction-springdsl/pom.xml, interaction-dynamic-loader/pom.xml, interaction-media-hal/pom.xml, interaction-media-odata-xml/pom.xml, interaction-media-xhtml/pom.xml, interaction-odata4j-ext/pom.xml, interaction-parent/pom.xml, interaction-sdk-archetype/pom.xml, interaction-sdk-plugin/pom.xml, interaction-sdk-rim-plugin/pom.xml, interaction-sdk-test/pom.xml, interaction-sdk/pom.xml, interaction-winkext/pom.xml, pom.xml
created new profile in pom files to enable IRIS CodeCoverage
=> Created profile to run CodeCoverage with SONAR

interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/FasterFlatResourceSetBasedAllContainersState.java, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/FasterResourceSetBasedAllContainersStateProvider.java, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/RIMDslRuntimeModule.java, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/RIMDslRuntimeModuleSwagger.java
This is essentially a backport of a performance improvement in XText 2.9.0
into what we are using here.
=> Workaround for performance bottleneck in XText

interaction-examples/interaction-hateoas-banking/src/main/java/com/temenos/interaction/example/hateoas/banking/DaoHibernate.java, interaction-examples/interaction-hateoas-dynamic/src/main/java/com/temenos/interaction/example/hateoas/dynamic/Persistence.java, interaction-examples/interaction-hateoas-simple/pom.xml, interaction-examples/interaction-hateoas-simple/src/main/java/com/temenos/interaction/example/hateoas/simple/Persistence.java, interaction-examples/interaction-mashup-streaming/src/main/java/com/temenos/interaction/example/mashup/streaming/GETProfileCommand.java, interaction-examples/interaction-mashup-streaming/src/main/java/com/temenos/interaction/example/mashup/streaming/Persistence.java, interaction-examples/interaction-mashup-twitter/src/main/java/com/temenos/interaction/example/mashup/twitter/Persistence.java, interaction-examples/interaction-odata-northwind/src/test/java/com/interaction/example/odata/northwind/AbstractNorthwindRuntimeTest.java, interaction-sdk/src/main/java/com/temenos/interaction/sdk/util/ResponderDBUtils.java, interaction-test/pom.xml, interaction-test/src/main/java/com/temenos/interaction/test/AbstractRuntimeTest.java
Consolidating logging to only use SLF4J.
=> Standardize logging to be SLF4J.

interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/SpringDSLResourceStateProvider.java
Move the loading of resources into an inner class to track what loads
were attempted so that failures can be accurately logged.
Without this, it is very difficult to diagnose resource loading problems
=> Better logging of resource loading problems.

interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestHALProvider.java, interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomEntityEntryFormatWriter.java
This doesn't fix all the problems in HALProvider; it needs a complete test suite and more work. But it fixes some things that didn't work last week.
=> Make entity output in hal+json fully recursive

interaction-commands-jdbc/pom.xml, interaction-jdbc-producer/pom.xml, interaction-parent/pom.xml
Add new modules to parent .pom.xml
Fix some versioning issues.
=> Follow up to pull a39aa996a090823afca99198677a067b7e67d7c0.

interaction-dsl/com.temenos.interaction.rimdsl.tests/src/com/temenos/interaction/rimdsl/GeneratorSpringPRDTest.java, interaction-dsl/com.temenos.interaction.rimdsl/META-INF/MANIFEST.MF, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/generator/RIMDslGenerator.xtend
E.g."Who & Why" -> "Who &amp; Why"
=> Escape XML special characters in transition labels.

interaction-media-hal/pom.xml, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestHALProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestNesting.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestRepresentation.java, interaction-media-hal/src/test/resources/logback.xml
Works with OEntity objects only, and only output is supported.
Entity and input still to do
=> Partial support for complex types in hal+json

interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestNesting.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestRepresentation.java
Last changes to HAL related projects broke the build on Java 8.
This has been fixed.
=> Fixed tests of HAL to work in Java 8

interaction-dynamic-loader/src/main/java/com/temenos/interaction/loader/properties/ReloadablePropertiesFactoryBean.java
Added support for specifying the location of the configuration refresh mechanism's index file as a system property. Also removed a large amount of dead code from the class.
Once IRIS supports pluggable strategies for loading configuration, including a non caching implementation, then this code should be removed.
=> Making the configuration refresh mechanism work on JBoss (and probably other servers)

interaction-examples/interaction-hateoas-banking/src/test/java/com/interaction/example/hateoas/banking/HypermediaITCase.java, interaction-examples/interaction-hateoas-dynamic/pom.xml, interaction-examples/interaction-hateoas-dynamic/src/test/java/com/interaction/example/hateoas/simple/HypermediaITCase.java, interaction-examples/interaction-hateoas-restbucks/src/test/java/com/interaction/example/hateoas/restbucks/LinkRelationsITCase.java, interaction-examples/interaction-hateoas-simple/src/test/java/com/interaction/example/hateoas/simple/HypermediaITCase.java, interaction-examples/interaction-hateoas-simple/src/test/java/com/interaction/example/hateoas/simple/MultipleGetITCase.java, interaction-examples/interaction-mashup-streaming/src/test/java/com/temenos/interaction/example/mashup/streaming/HypermediaITCase.java, interaction-examples/interaction-mashup-twitter/src/test/java/com/interaction/example/mashup/twitter/HypermediaITCase.java, interaction-media-hal/pom.xml, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestHALProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestRepresentation.java, interaction-parent/pom.xml
Add support for nested JSON objects to HALProvider.
=> Hal builder fix2

interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestHALProvider.java
Added Null check for link in buildHalResource() before using it.
=> Added a null check before calling methods of resource embedded as link

interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
The HAL parser will return a null entity but not throw an exception.
This is needed where we POST with no body to create a new entity.
=> Permit an empty request body with hal-json content type.

interaction-examples/interaction-hateoas-banking/src/test/java/com/interaction/example/hateoas/banking/HypermediaITCase.java, interaction-examples/interaction-hateoas-restbucks/src/test/java/com/interaction/example/hateoas/restbucks/LinkRelationsITCase.java, interaction-examples/interaction-hateoas-simple/src/test/java/com/interaction/example/hateoas/simple/CacheITCase.java, interaction-examples/interaction-hateoas-simple/src/test/java/com/interaction/example/hateoas/simple/HypermediaITCase.java, interaction-examples/interaction-mashup-streaming/src/test/java/com/temenos/interaction/example/mashup/streaming/HypermediaITCase.java, interaction-examples/interaction-mashup-twitter/src/test/java/com/interaction/example/mashup/twitter/HypermediaITCase.java, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALMediaType.java, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/metadata/MetaDataProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/EmptyEntity.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestHALProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestNesting.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/metadata/TestMetadataProvider.java, interaction-parent/pom.xml
This includes:
* JSON output of structured OEntity entities
* JSON input of structured entities
* Support for application/json media type
* JSON output of structured Entity entities
* Support for embedded links
=> backport of json fixes to 0.4 branch

interaction-core/src/main/java/com/temenos/interaction/core/cache/CacheConcurrentImpl.java, interaction-core/src/main/java/com/temenos/interaction/core/cache/CacheExtended.java, interaction-core/src/main/java/com/temenos/interaction/core/loader/LoadingStrategy.java, interaction-core/src/main/java/com/temenos/interaction/core/loader/ResourceStateLoadingStrategy.java, interaction-core/src/main/java/com/temenos/interaction/core/loader/SpringResourceStateLoadingStrategy.java, interaction-core/src/test/java/com/temenos/interaction/core/cache/TestCacheConcurrentImpl.java, interaction-core/src/test/java/com/temenos/interaction/core/loader/TestSpringResourceStateLoadingStrategy.java, interaction-core/src/test/resources/IRIS-empty-PRD.xml, interaction-core/src/test/resources/IRIS-testResources-PRD.xml, interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/EagerSpringDSLResourceStateProvider.java, interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/SpringDSLResourceStateProvider.java, interaction-dsl/interaction-springdsl/src/main/resources/IRIS-SpringDSL-main.xml, interaction-dsl/interaction-springdsl/src/test/java/com/temenos/interaction/springdsl/TestEagerSpringDSLResourceStateProvider.java, interaction-dsl/interaction-springdsl/src/test/java/com/temenos/interaction/springdsl/TestSpringDSLResourceStateProvider.java, interaction-dsl/interaction-springdsl/src/test/resources/IRIS-SpringDSL-test.xml, interaction-dsl/interaction-springdsl/src/test/resources/com/temenos/interaction/springdsl/TestEagerSpringDSLResourceStateProvider-context.xml, interaction-dynamic-loader/src/test/java/com/temenos/interaction/loader/properties/resource/action/TestIRISResourceChangedAction.java, interaction-dynamic-loader/src/test/java/com/temenos/interaction/loader/properties/resource/action/TestIRISResourceLoadedAction.java, interaction-examples/interaction-odata-airline/src/main/resources/logback.xml
Some private methods in the SpringDSLResourceStateProvider (lazy provider) where made protected in order to re-use them in the EagerSpringDSLResourceStateProvider. In any case, this is a temporary solution until we do major re-factoring.
=> Added interfaces for caching and loading strategies, providing an implementation of an eager resource state provider.

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/ResourceStateMachine.java
fixing the rel for dynamic drill down.
=> Fix in resourceStateMachine for bug 1416712.

interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java, interaction-media-hal/src/test/java/com/temenos/interaction/media/hal/TestNesting.java
This is, I think, the last remaining case of missing JSON support; we can now serialize Entities or OEntities, singly or in collections.
=> Support collections of Entities in JSON output

interaction-examples/interaction-odata-airline/Orchestra.rim, interaction-examples/interaction-odata-airline/hot-deploy-dir/readme.txt, interaction-examples/interaction-odata-airline/src/main/resources/META-INF/spring-beans.xml, interaction-examples/interaction-odata-airline/src/main/resources/metadata.xml
=> Revert "Increase wait to 3 minutes"

interaction-sdk-test/src/test/java/com/temenos/interaction/sdk/InteractionSDKTest.java
=> Revert "Server startup takes slightly longer with dynamic RIM loader changes …"

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/HypermediaTemplateHelper.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestHypermediaTemplateHelper.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestResourceStateMachine.java
Customer Derivatives position home page has missing drill down.
Feature to capture the multivalued fields to build the Links in HypermediaTemplateHelper.
Only the first record is used to build the links, even if the array have more more values.
=> RTC1642726

interaction-commands-odata/src/main/java/com/temenos/interaction/commands/odata/GETEntitiesCommand.java, interaction-commands-odata/src/test/java/com/temenos/interaction/commands/odata/TestGETEntitiesCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/command/InteractionProducerException.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
Catching and returning the field errors (Mandatory input missing) from T24Producer
=> Producer errors not included in response

interaction-commands-odata/src/main/java/com/temenos/interaction/commands/odata/GETEntitiesCommand.java, interaction-commands-odata/src/test/java/com/temenos/interaction/commands/odata/TestGETEntitiesCommand.java
Change for returning a EntityResource instead of a collection for errors raised on Producer
=> Change for returning a EntityResource instead of a collection

interaction-commands-odata/src/main/java/com/temenos/interaction/commands/odata/GETEntitiesCommand.java, interaction-commands-odata/src/main/java/com/temenos/interaction/commands/odata/GETEntityCommand.java, interaction-commands-odata/src/test/java/com/temenos/interaction/commands/odata/TestGETEntitiesCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/command/InteractionProducerException.java
The Producer will decide the http status code and the error details on the error entity.
=> Change for producer errors raising

interaction-commands-solr/src/main/java/com/temenos/interaction/commands/solr/SolrSearchCommand.java
Temporary fix to get BRP working again. Task will be left open so that a full fix can be done once underlying architectural issues have been understood.
=> RTC1671119: IRIS SOLR support no longer works

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/HypermediaTemplateHelper.java
Fix HypermediaTemplateHelper logic so that parameters will not be overwritten.
=> RTC #1673751

useragent-generic-java/src/main/java/com/temenos/useragent/generic/DefaultInteractionSession.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/Entities.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/InteractionSession.java, useragent-generic-java/src/test/java/com/temenos/interaction/test/TestUpdateInput.java
a method to unset any property previously set
=> adding methods to access item and collection entities from response with

interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/ODataLinkInterceptor.java, interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestODataLinkInterceptor.java
Updating the link relation generation logic to handle transition having a multivalue param to non-collection target resource .
=> Rel update

interaction-core/pom.xml, interaction-examples/interaction-hateoas-banking/pom.xml, interaction-examples/interaction-hateoas-simple/pom.xml, interaction-examples/interaction-mashup-streaming/pom.xml, interaction-examples/interaction-odata-embedded/pom.xml, interaction-examples/interaction-odata-error/pom.xml, interaction-examples/interaction-odata-etag/pom.xml, interaction-parent/pom.xml, useragent-examples/useragent-odata-html5/pom.xml, useragent-examples/useragent-swagger-ui/pom.xml
Update the Javax Servlet API version from 2.5 to 3.0.1
=> Update Javax Servlet API version

useragent-generic-java/pom.xml, useragent-generic-java/src/main/java/com/temenos/useragent/generic/Url.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/http/DefaultHttpClient.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/http/DefaultHttpExecutor.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/http/HttpClient.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/http/HttpMethod.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/UrlWrapper.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/http/DefaultHttpExecutorTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/internal/UrlWrapperTest.java
Support for HTTP DELETE added to useragent-generic-java.
=> Add delete method to integration test framework

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/Link.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkToFieldAssociation.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkToFieldAssociationImpl.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/Transition.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLink.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkGenerator.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkToFieldAssociation.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestResourceStateMachine.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestTransition.java, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/RIMDsl.xtext, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/generator/RIMDslGenerator.xtend, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/generator/RIMDslGeneratorSpringPRD.xtend, interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/TransitionFactoryBean.java, interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/ODataLinkInterceptor.java, interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestODataLinkInterceptor.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/DefaultEntityWrapper.java
multivalue changes for RTC 1728630 (AA.PRODUCT.CATALOG)
=> Including multivalue changes for RTC 1728630

useragent-generic-java/src/main/java/com/temenos/useragent/generic/context/ContextFactory.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/http/DefaultHttpClient.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/http/DefaultHttpExecutor.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/http/HttpHeader.java
HTTP 204 responses no longer cause NullPointerExceptions in
DefaultHttpClient.
=> Add support for HTTP 204 and fix HttpHeader issues

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/Link.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkToFieldAssociation.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkToFieldAssociationImpl.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLink.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkGenerator.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkToFieldAssociation.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestResourceStateMachine.java, interaction-examples/interaction-odata-airline/src/test/java/com/interaction/example/odata/airline/ODataAssociationsITCase.java, interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/ODataLinkInterceptor.java, interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestODataLinkInterceptor.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/DefaultEntityWrapper.java
Link generation update - reading label field from enquiry drilldown
=> Link generation update - reading label field from enquiry drilldown

interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/ODataLinkInterceptor.java, interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestODataLinkInterceptor.java
Changing the link relation generation logic for composite resource
=> Rel generation update for composite resource

interaction-winkext/src/main/java/com/temenos/interaction/winkext/LazyResourceDelegate.java, interaction-winkext/src/test/java/com/temenos/interaction/winkext/TestLazyServiceRootFactory.java
=> Correctly handle resource lookup failure when processing a lazy resource

interaction-core/pom.xml, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HeaderHelper.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/ResponseWrapper.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkGenerator.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkGeneratorImpl.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHeaderHelper.java, interaction-parent/pom.xml
This change updates IRIS's location header to the destination of a fully resolved chain of automatic transitions and appends any parameters that were resolved during this process.
=> Set location response header to the final destination of all participating automatic transitions

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHTTPHypermediaRIM.java
This commit refines the behaviour of autotransition traversal to prevent
headers from being set multiple times and to prevent commands from
needlessly being executed.
=> Traverse autotransitions iteratively

interaction-odata4j-ext/src/main/java/org/odata4j/format/xml/AtomFeedFormatParserExt.java, interaction-odata4j-ext/src/main/java/org/odata4j/stax2/staximpl/StaxXMLInputFactory2Ext.java
This change updates the Stax XML reader to prevent XXE and billion laugh attacks
=> Prevent internal and external entity injection

interaction-dsl/com.temenos.interaction.rimdsl.parent/pom.xml, interaction-examples/interaction-hateoas-restbucks/pom.xml, interaction-examples/interaction-mashup-twitter/src/main/java/com/temenos/interaction/example/mashup/twitter/OAuthRequestor.java, interaction-examples/interaction-mashup-twitter/src/main/java/com/temenos/interaction/example/mashup/twitter/Twitter4JConsumer.java, interaction-examples/interaction-mashup-twitter/src/main/java/com/temenos/interaction/example/mashup/twitter/TwitterMashupException.java, interaction-examples/interaction-odata-embedded/pom.xml, interaction-examples/interaction-odata-error/pom.xml, interaction-examples/interaction-odata-etag/pom.xml, interaction-parent/pom.xml, interaction-sdk-archetype/src/main/resources/archetype-resources/pom.xml
Fix the maven compiler plugin properties
Code clean on interaction example mashup twitter
=> Code clean

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java
Changing logging level to ERROR when handling InteractionException.
=> Rtc 1780207

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/ResourceStateMachine.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-parent/pom.xml
=> Add guards to logging in handleRequest(), buildResponse() and injectLinks()

useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/AtomLinkHandler.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/AtomLinkHandlerTest.java
Adding base uri to embedded link
=> Including base uri in embedded link

interaction-odata4j-ext/src/main/java/com/temenos/interaction/odataext/entity/MetadataOData4j.java
Previous behaviour was that the code failed with a NullPointerException and didn't identify the cause. Also renamed logger to LOGGER per standard Java naming conventions and made appropriate use of SLF4J log templates.
=> Log what is missing when initializing meta data

interaction-core/src/main/java/com/temenos/interaction/core/command/InteractionContext.java, interaction-core/src/main/java/com/temenos/interaction/core/command/NoopGETCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java, interaction-core/src/test/java/com/temenos/interaction/core/command/TestNoopGETCommand.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestResponseHTTPHypermediaRIM.java
Change the NoopGETCommand.java to pass the input query parameters to the output query parameters in order to create the transitions using the same context query
=> Enhancement for the NoopGETCommand

interaction-core/src/main/java/com/temenos/interaction/core/rim/HeaderHelper.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHeaderHelper.java
Fixes issues arising if an incoming MultivaluedMap contains empty List objects.
=> Append keys with blank values to Location header

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/ResponseWrapper.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/SequentialResourceRequestHandler.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestResponseHTTPHypermediaRIM.java
This pull request resolves known issues with automatic transitions and query parameters in a request to a resource that has multiple [transitive] automatic transitions to other resources.
=> Auto transition issue

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/ResourceStateMachine.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestLinkGeneratorImpl.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestResourceStateMachine.java
Keep all input arguments when processing dynamic links
=> Keep all input arguments when processing dynamic links

useragent-generic-java/pom.xml, useragent-generic-java/src/main/java/com/temenos/useragent/generic/DefaultInteractionSession.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/InteractionSession.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/DefaultEntityWrapper.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/DefaultPayloadWrapper.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/EntityHandler.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/EntityWrapper.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/NullEntityWrapper.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/AtomEntryHandler.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/AtomUtil.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/AtomXmlContentHandler.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/PlainTextEntityHandler.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/AtomEntryHandlerTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/AtomLinkHandlerTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/AtomUtilTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/AtomXmlContentHandlerTest.java, useragent-generic-java/src/test/resources/atom_entry_content_update.xml
- Supporting adding new child properties to the content
- Removing specific child properties from the content
=> Handling properties for atom xml content in useragent-generic-java

interaction-commands-odata/src/main/java/com/temenos/interaction/commands/odata/GETEntitiesCommand.java, interaction-commands-odata/src/main/java/com/temenos/interaction/commands/odata/GETEntityCommand.java, interaction-commands-odata/src/test/java/com/temenos/interaction/commands/odata/TestCommandHelper.java, interaction-commands-odata/src/test/java/com/temenos/interaction/commands/odata/TestGETEntitiesCommand.java, interaction-commands-odata/src/test/java/com/temenos/interaction/commands/odata/TestGETEntityCommand.java
Enhancement to allow the usage of the odata feature $select if is present as action property
=> Task 1846700

interaction-core/src/main/java/com/temenos/interaction/core/rim/HeaderHelper.java, interaction-core/src/main/java/com/temenos/interaction/core/web/RequestContext.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHeaderHelper.java, interaction-core/src/test/java/com/temenos/interaction/core/web/TestRequestContext.java
=> 1856475 header case insensitive search functionality

interaction-core/src/main/java/com/temenos/interaction/core/MultivaluedMapHelper.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-core/src/test/java/com/temenos/interaction/core/TestMultivaluedMapHelper.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestResponseHTTPHypermediaRIM.java
This commit adds a utility class for manipulating and transforming MultivaluedMap objects and a utility method for merging two MultivaluedMap objects.
=> 1859482 utility method to merge MultivaluedMaps

useragent-examples/useragent-swagger-ui/src/main/webapp/META-INF/resources/swagger.jsp, useragent-examples/useragent-swagger-ui/src/test/java/com/temenos/useragent/example/swagger/SwaggerTest.java
Initial swagger UI page JSP refactor (test included) to use the new swagger UI v2 and replace the url input form field with a dropdown list containing all the json documents available on the war file (api-docs folder)
=> Swagger JSP refactor

useragent-generic-java/src/main/java/com/temenos/useragent/generic/http/DefaultHttpClient.java
Logger was throwing and catching a Fatal XML parse error for every GET request
=> Fix some logging in useragent-generic-java

interaction-core/src/main/java/com/temenos/interaction/core/command/InteractionProducerException.java, interaction-core/src/main/java/com/temenos/interaction/core/entity/EntityMetadata.java, interaction-core/src/main/java/com/temenos/interaction/core/entity/vocabulary/terms/TermValueType.java, interaction-core/src/test/java/com/temenos/interaction/core/entity/TestMetadata.java, interaction-dsl/com.temenos.interaction.rimdsl.generator/src/main/java/com/temenos/interaction/rimdsl/generator/launcher/Generator.java, interaction-dsl/com.temenos.interaction.rimdsl.tests/src/Simple.rim, interaction-dsl/com.temenos.interaction.rimdsl.tests/src/apiSimple.rim, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/generator/RIMDslGeneratorSwagger.xtend, useragent-examples/useragent-swagger-ui/src/main/webapp/META-INF/resources/swagger.jsp
1. Enable Swagger to show the correct data types defined by the metadata term type values
2. Remove the static companyId defined on web.xml and make it a user input field on swagger UI
3. Change the swagger notation identifier from "Api" to "Annotation"
=> Changes for Swagger generation

interaction-core/src/main/java/com/temenos/interaction/core/entity/vocabulary/TermFactory.java, interaction-core/src/main/java/com/temenos/interaction/core/entity/vocabulary/terms/TermDescription.java, interaction-core/src/test/java/com/temenos/interaction/core/entity/vocabulary/TestTermFactory.java, interaction-dsl/com.temenos.interaction.rimdsl.generator/src/main/java/com/temenos/interaction/rimdsl/generator/launcher/Generator.java, interaction-dsl/com.temenos.interaction.rimdsl.generator/src/test/java/com/temenos/interaction/rimdsl/generator/launcher/GeneratorTest.java, interaction-dsl/com.temenos.interaction.rimdsl/src/com/temenos/interaction/rimdsl/generator/RIMDslGeneratorSwagger.xtend, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
**1866706:**
Change on swagger generator to bring entity property term description an enrich the information present on the open API document
=> 1866706 - Usage the Term Description to enrich the swagger document

interaction-core/src/main/java/com/temenos/interaction/core/entity/vocabulary/TermFactory.java, interaction-core/src/main/java/com/temenos/interaction/core/entity/vocabulary/terms/TermDescription.java, interaction-core/src/test/java/com/temenos/interaction/core/entity/vocabulary/TestTermFactory.java, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
**1866706:**
Added a new term to IRIS. Term Description to store descriptions for the properties inside a entity.
=> 1866706 - New Term: Description

interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/SpringDSLResourceStateProvider.java, interaction-dynamic-loader/src/main/java/com/temenos/interaction/loader/properties/ReloadablePropertiesFactoryBean.java, interaction-dynamic-loader/src/main/resources/META-INF/com/temenos/interaction/loader/IRIS-Dynamic-Load.xml, interaction-dynamic-loader/src/test/java/com/temenos/interaction/loader/properties/ReloadablePropertiesFactoryBeanTest.java
Hi @ssethupathi , can you review this?
=> RTC-1927022 - app-path check added to set lastChangeFile

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHTTPHypermediaRIM.java
@ssethupathi Please review this.
=> 1985020 split before decode

interaction-core/src/main/java/com/temenos/interaction/core/resource/ResourceMetadataManager.java
@ssethupathi Please can you review and merge.
=> RTC-1760321 - logger level change for missing metadata messages

interaction-examples/interaction-hateoas-banking/pom.xml, interaction-examples/interaction-hateoas-dynamic/pom.xml, interaction-examples/interaction-hateoas-restbucks/pom.xml, interaction-examples/interaction-hateoas-simple/pom.xml, interaction-examples/interaction-mashup-streaming/pom.xml, interaction-examples/interaction-odata-airline/pom.xml, interaction-examples/interaction-odata-airline/src/test/hot-deploy-demo/pom.xml, interaction-examples/interaction-odata-embedded/pom.xml, interaction-examples/interaction-odata-error/pom.xml, interaction-examples/interaction-odata-etag/pom.xml, interaction-examples/interaction-odata-multicompany/pom.xml, interaction-examples/interaction-odata-northwind/pom.xml, interaction-examples/interaction-odata-notes/pom.xml, interaction-jdbc-producer/pom.xml, interaction-sdk-test/pom.xml
BRP_IRIS_0.13.8_Changes to version files
=> BRP_IRIS_0.13.8_Changes to version files

useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/HalJsonEntityHandler.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/HalJsonEntityHandlerTest.java, useragent-generic-java/src/test/resources/haljson_item_with_all_properties.json
Sethu please review and pull if acceptable
=> fixes #537 HAL handler now processes the representation and can replace properties.

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java
RTC1866488 . Fixing classCastException handling EntityResource
=> Fixing classCastException handling EntityResource

interaction-core/src/test/java/com/temenos/interaction/core/rim/TestSequentialResourceRequestHandler.java, interaction-examples/interaction-hateoas-dynamic/src/test/java/com/interaction/example/hateoas/simple/HypermediaITCase.java, interaction-examples/interaction-hateoas-simple/src/test/java/com/interaction/example/hateoas/simple/HypermediaITCase.java, interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
This pull request fixes the issue reported in https://github.com/temenostech/IRIS/issues/549
=> HAL provider issue when collection of beans returned (fixes 549)

useragent-examples/useragent-swagger-ui/src/main/webapp/META-INF/resources/swagger.jsp
The method getRealPath(String) from the type ServletRequest is deprecated and doesn't work in WebLogic without a domain configuration change.
Replaced with an alternative way of accessing the open API documents in runtime.
=> [Enhancement] Swagger JSP enhancement

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/ResourceStateMachine.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/expression/ExpressionEvaluator.java, interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/transition/AutoTransitioner.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/AbortOnErrorWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/AbortOnErrorWorkflowStrategyCommandBuilder.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/InteractionWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/InteractionWorkflowStrategyCommandBuilder.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/NaiveWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/RetryWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/WorkflowCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/WorkflowCommandBuilderFactory.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/WorkflowCommandBuilderProvider.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestResourceStateMachine.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHTTPHypermediaRIM.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestResponseHTTPHypermediaRIM.java, interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomEntryFormatWriter.java, interaction-winkext/src/main/java/com/temenos/interaction/winkext/LazyServiceRootFactory.java
evaluation during auto transitioning and to inject workflow command execution
behaviour
=> RTC1954843 backward compatibility to support expression

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java
add POST method for /aapopulate request.
=> RTC-2068133-AA_Populate_Fix for /aapopulate or /new link issue

interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPResourceInteractionModel.java
2125243  [BRP-SAT]Product Condition while trying to Delete gives error
=> 2125243 accept header added for delete method

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/LinkGeneratorImpl.java
=> Revert AA_Populate_Fix for /aapopulate or /new link issue"

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/HypermediaTemplateHelper.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestHypermediaTemplateHelper.java
RTC-2192855 - Filter parameter is not generated properly for MATCHES operator in rim files
=> RTC-2192855 - Filter parameter is not generated properly for MATCHES operator in rim files

interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/SpringDSLResourceStateProvider.java
=> fix - classpath lookup for *-PRD.xml

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/HypermediaTemplateHelper.java, interaction-core/src/test/java/com/temenos/interaction/core/hypermedia/TestHypermediaTemplateHelper.java
RTC - 2193155 - Begins with, Does not Begin with, Ends with, Does not End with and Not Between selection criteria are not properly fetching the results for the enquiries
=> RTC - 2193155 - Selection criteria are not properly fetching the results for the enquiries

useragent-generic-java/src/main/java/com/temenos/useragent/generic/DefaultInteractionSession.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/InteractionSession.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/context/ContentTypeHandlers.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/context/ContextFactory.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/DefaultEntityWrapper.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/EntityHandler.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/internal/EntityWrapper.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/HalJsonEmbeddedPayloadHandler.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/HalJsonEntityHandler.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/HalJsonUtil.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/JsonEntityHandler.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/JsonPayloadHandler.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/JsonUtil.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/AtomEntryHandlerTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/HalJsonEntityHandlerTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/HalJsonLinkHandlerTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/HalJsonPayloadHandlerTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/JsonEntityHandlerTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/JsonPayloadHandlerTest.java, useragent-generic-java/src/test/java/com/temenos/useragent/generic/mediatype/JsonUtilTest.java, useragent-generic-java/src/test/resources/haljson_item_with_inline_item.json, useragent-generic-java/src/test/resources/json_collection_with_two_items.json
- JSON Payload and Entity handler added
- Support to set primitive data-type in entity
**Defect 2287021**: Unable to set/update any values other than String data types on json request in apipecunia-IRIS2 cucumber automation
**Defect 2269174**: Collection Size is zero showing for Particular Property in Json Array type Collection Response in usergeneric-java project
**Defect 2269174**: Collection Size is zero showing for Particular Property in Json Array type Collection Response in usergeneric-java project
**Defect 2269244**: halbuilder-json-4.0.3 restricts the fieldnames having Null values in IRIS2 entity response
=> user-agent JSON handler added and set primitive supported

interaction-core/src/main/java/com/temenos/interaction/core/entity/EntityProperties.java, interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomEntityEntryFormatWriter.java, interaction-odata4j-ext/src/main/java/org/odata4j/format/xml/AtomFeedFormatParserExt.java
Support response format for new Bulk API single/bulk response.
=> Support response format for new Bulk API single/bulk response.

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/transition/AutoTransitioner.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/AbortOnErrorWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/NaiveWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/RetryWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/TransitionWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/WorkflowCommand.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestResponseHTTPHypermediaRIM.java
- Current IRIS workflow handles only successful auto transition evaluation.
- Nordea API heavily rely on auto transition response status, both success and failure transitions.
- This change returns the auto transition failure indication in the response status.
- Change considers only interaction command workflows and ignores transition command workflows to support backward compatibility.
=> Nordea API 201708 migration changes

interaction-odata4j-ext/src/main/java/org/odata4j/format/xml/AtomFeedFormatParserExt.java
=> Revert "201712 unable to start pw"

interaction-core/src/main/java/com/temenos/interaction/core/hypermedia/transition/AutoTransitioner.java, interaction-core/src/main/java/com/temenos/interaction/core/rim/HTTPHypermediaRIM.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/AbortOnErrorWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/NaiveWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/RetryWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/TransitionWorkflowStrategyCommand.java, interaction-core/src/main/java/com/temenos/interaction/core/workflow/WorkflowCommand.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestHTTPHypermediaRIM.java, interaction-core/src/test/java/com/temenos/interaction/core/rim/TestResponseHTTPHypermediaRIM.java
- Backward compatibility update to deep scan workflow commands for transition command existence
- Current IRIS workflow handles only successful auto transition evaluation.
- Nordea API heavily rely on auto transition response status, both success and failure transitions.
- This change returns the auto transition failure indication in the response status.
- Change considers only interaction command workflows and ignores transition command workflows to support backward compatibility.
=> backward compatibility update to deep scan workflow commands when checking for transition command existence & api migration changes

interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/SpringDSLResourceStateProvider.java
Convert level of multiple states bound logs from warning to debug
=> Convert level of multiple states bound logs from warning to debug

interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomEntryFormatWriter.java, interaction-media-odata-xml/src/main/java/com/temenos/interaction/media/odata/xml/atom/AtomXMLProvider.java, interaction-media-odata-xml/src/test/java/com/temenos/interaction/media/odata/xml/atom/TestAtomXMLProvider.java
=> Extract embedded resource LinkId and use it for link generation with id attribute 

interaction-parent/pom.xml
=> Spring version upgraded.

interaction-examples/interaction-hateoas-banking/src/main/java/com/temenos/interaction/example/hateoas/banking/POSTFundTransferCommand.java, useragent-examples/useragent-odata-html5/src/main/webapp/META-INF/resources/Scripts/jquery-1.8.2.js, useragent-examples/useragent-odata-html5/src/main/webapp/META-INF/resources/Scripts/jquery-ui.js, useragent-examples/useragent-odata-html5/src/main/webapp/META-INF/resources/explorer.jsp
=> IRIS Security testing issues

interaction-core/src/main/java/com/temenos/interaction/core/entity/MetadataParser.java, interaction-sdk/src/main/java/com/temenos/interaction/sdk/util/ReferentialConstraintParser.java, useragent-generic-java/src/main/java/com/temenos/useragent/generic/mediatype/AtomUtil.java
Validating XML before parsing.
=> Validating XML before parsing

interaction-core/src/main/java/com/temenos/interaction/core/entity/MetadataParser.java, interaction-sdk/src/main/java/com/temenos/interaction/sdk/util/ReferentialConstraintParser.java
To avoid External Entity Injection.
=> Fix for External Entity Injection

interaction-core/src/main/java/com/temenos/interaction/metadata/resource/MetadataResourceProvider.java, interaction-dsl/interaction-springdsl/src/main/java/com/temenos/interaction/springdsl/DatabaseSystemResourceStateLoader.java
=> EDP - Preload models feature

interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
Removed new instantiation of UriInfoImpl to avoid new stack frame creation for each function call which impact the performance.
=> Removed local new instantiation of UriInfoImpl 

interaction-media-hal/src/main/java/com/temenos/interaction/media/hal/HALProvider.java
Removed new instantiation of UriInfoImpl to avoid new stack frame creation for each function call which impact the performance.
=> Removed local new instantiation of UriinfoImpl

interaction-dsl/com.temenos.interaction.rimdsl.parent/pom.xml
As suggested in the thread upgrading the version of Xtend is helping us resolve the issue 
https://github.com/eclipse/xtext/issues/1373
=> UTP Build failure: xtend plugin dependency changes
